Repository CivMC/Civ, pull requests merged in 2024-10, with the labels that each got.

#583 Add MuteListCommand
  plugins/jukealert-paper/src/main/java/com/untamedears/jukealert/commands/JACommandManager.java
  plugins/jukealert-paper/src/main/java/com/untamedears/jukealert/commands/MuteListCommand.java
Labels: Category: Feature

#632 Prevent reinforced concrete powder hardening
  plugins/citadel-paper/src/main/java/vg/civcraft/mc/citadel/listener/BlockListener.java
Labels: Category: Bug, Priority: Medium

#633 Prevent stripping logs & copper from damaging reinforcement
  plugins/citadel-paper/src/main/java/vg/civcraft/mc/citadel/listener/EntityListener.java
Labels: Category: Bug, Priority: Medium

#634 Add BuildLimits hack
  ansible/files/paper-config/plugins/SimpleAdminHacks/config.yml
  plugins/simpleadminhacks-paper/src/main/java/com/programmerdan/minecraft/simpleadminhacks/SimpleAdminHacks.java
  plugins/simpleadminhacks-paper/src/main/java/com/programmerdan/minecraft/simpleadminhacks/configs/buildlimit/BuildLimitsConfig.java
  plugins/simpleadminhacks-paper/src/main/java/com/programmerdan/minecraft/simpleadminhacks/configs/buildlimit/LimitType.java
  plugins/simpleadminhacks-paper/src/main/java/com/programmerdan/minecraft/simpleadminhacks/framework/utilities/BuildLimit.java
  plugins/simpleadminhacks-paper/src/main/java/com/programmerdan/minecraft/simpleadminhacks/hacks/BuildLimits.java
  plugins/simpleadminhacks-paper/src/main/resources/config.yml
Labels: Category: Feature

#650 Add flower/decorated pots to aesthetic factory
  ansible/files/paper-config/plugins/FactoryMod/config.yml
Labels: Category: Feature, Priority: Low

#649 Add /emf toggle dogfact
  ansible/files/paper-config/plugins/SimpleAdminHacks/config.yml
Labels: Category: Feature, Priority: Low

#619 Prevent pearled people from pearling others
  ansible/files/paper-config/plugins/ExilePearl/config.yml
  plugins/exilepearl-paper/src/main/java/com/devotedmc/ExilePearl/Lang.java
  plugins/exilepearl-paper/src/main/java/com/devotedmc/ExilePearl/config/PearlConfig.java
  plugins/exilepearl-paper/src/main/java/com/devotedmc/ExilePearl/core/CorePearlConfig.java
  plugins/exilepearl-paper/src/main/java/com/devotedmc/ExilePearl/core/CorePearlManager.java
  plugins/exilepearl-paper/src/main/resources/config.yml
Labels: Category: Feature

#642 Snitchlog Fixes
  plugins/jukealert-paper/src/main/java/com/untamedears/jukealert/listener/LoggableActionListener.java
  plugins/jukealert-paper/src/main/java/com/untamedears/jukealert/model/actions/LoggedActionFactory.java
  plugins/jukealert-paper/src/main/java/com/untamedears/jukealert/model/actions/abstr/LoggableBlockAction.java
  plugins/jukealert-paper/src/main/java/com/untamedears/jukealert/model/actions/impl/DismountEntityAction.java
  plugins/jukealert-paper/src/main/java/com/untamedears/jukealert/model/actions/impl/EditSignAction.java
  plugins/jukealert-paper/src/main/java/com/untamedears/jukealert/model/actions/impl/MountEntityAction.java
  plugins/jukealert-paper/src/main/java/com/untamedears/jukealert/util/JAUtility.java
Labels: Category: Technical Debt, Priority: High
