Repository CivMC/Civ, pull requests merged in 2024-11, with the labels that each got.

#606 Acidblock improvements
  plugins/citadel-paper/src/main/java/vg/civcraft/mc/citadel/CitadelUtility.java
  plugins/citadel-paper/src/main/java/vg/civcraft/mc/citadel/command/Acid.java
  plugins/citadel-paper/src/main/java/vg/civcraft/mc/citadel/command/ReinforcementsGUI.java
  plugins/citadel-paper/src/main/java/vg/civcraft/mc/citadel/listener/ModeListener.java
  plugins/citadel-paper/src/main/java/vg/civcraft/mc/citadel/model/AcidManager.java
Labels: Category: Feature

#656 Show pearl health value instead of percent
  plugins/exilepearl-paper/src/main/java/com/devotedmc/ExilePearl/ExilePearl.java
  plugins/exilepearl-paper/src/main/java/com/devotedmc/ExilePearl/command/CmdAdminSetHealth.java
  plugins/exilepearl-paper/src/main/java/com/devotedmc/ExilePearl/core/CoreExilePearl.java
  plugins/exilepearl-paper/src/main/java/com/devotedmc/ExilePearl/core/CoreLoreGenerator.java
  plugins/exilepearl-paper/src/main/java/com/devotedmc/ExilePearl/listener/PlayerListener.java
Labels: Category: Feature, Priority: Medium

#657 Allow ops to bypass pearled alt restrictions
  plugins/exilepearl-paper/src/main/java/com/devotedmc/ExilePearl/listener/BanStickListener.java
Labels: Category: Feature, Priority: Low
