Repository CivMC/Civ, pull requests merged in 2024-03, with the labels that each got.

#345 A partial fix for minecart derailment
  plugins/simpleadminhacks-paper/src/main/java/com/programmerdan/minecraft/simpleadminhacks/hacks/basic/AntiDerailment.java
  plugins/simpleadminhacks-paper/src/main/resources/config.yml
Labels: Category: Bug, Priority: High

#334 Fix horse stats being re-rolled on login
  plugins/simpleadminhacks-paper/src/main/java/com/programmerdan/minecraft/simpleadminhacks/hacks/basic/FasterHorses.java
Labels: Category: Bug, Priority: High

#335 Fix horse stats message double sending
  plugins/simpleadminhacks-paper/src/main/java/com/programmerdan/minecraft/simpleadminhacks/hacks/HorseStats.java
Labels: Category: Bug, Priority: Low

#353 Add skip existing reinforcements flag to ctar
  plugins/citadel-paper/src/main/java/vg/civcraft/mc/citadel/command/AreaReinforce.java
Labels: Category: Feature, Priority: High

#338 Deoxidise as many blocks as the tool in-hand can
  plugins/simpleadminhacks-paper/src/main/java/com/programmerdan/minecraft/simpleadminhacks/hacks/basic/CopperRail.java
Labels: Category: Feature, Priority: Medium

#354 Fix skin not carrying over on profile change
  plugins/namelayer-paper/src/main/java/vg/civcraft/mc/namelayer/misc/ProfileModifier.java
Labels: Category: Bug, Priority: Medium

#340 Remove WorldXZ
  plugins/civmodcore-paper/src/main/java/vg/civcraft/mc/civmodcore/world/WorldXZ.java
Labels: Category: Technical Debt, Priority: Low

#341 Remove ImmutableLocation
  plugins/civmodcore-paper/src/main/java/vg/civcraft/mc/civmodcore/world/ImmutableLocation.java
Labels: Category: Technical Debt, Priority: Low

#342 Remove ResourceUtils
  plugins/civmodcore-paper/src/main/java/vg/civcraft/mc/civmodcore/utilities/ResourceUtils.java
Labels: Category: Technical Debt, Priority: Low

#343 Remove JavaExtensions
  plugins/civmodcore-paper/src/main/java/vg/civcraft/mc/civmodcore/utilities/JavaExtensions.java
Labels: Category: Technical Debt, Priority: Low

#344 Remove ClassUtility
  plugins/civmodcore-paper/src/main/java/vg/civcraft/mc/civmodcore/utilities/ClassUtility.java
Labels: Category: Technical Debt, Priority: Low

#348 Fix to allow floor/ceiling buttons placed backwards to open doors
  plugins/citadel-paper/src/main/java/vg/civcraft/mc/citadel/listener/RedstoneListener.java
Labels: Category: Bug, Priority: Medium

#346 Fix player's current chat group not showing on join
  plugins/civchat2-paper/src/main/java/vg/civcraft/mc/civchat2/CivChat2Manager.java
  plugins/civchat2-paper/src/main/java/vg/civcraft/mc/civchat2/listeners/CivChat2Listener.java
Labels: Category: Bug, Priority: Low

#351 Prevent grass spread to reinforced dirt
  plugins/citadel-paper/src/main/java/vg/civcraft/mc/citadel/listener/BlockListener.java
Labels: Category: Bug, Priority: Low

#339 Create centralised player-name cache
  plugins/civmodcore-paper/src/main/java/vg/civcraft/mc/civmodcore/CivModCorePlugin.java
  plugins/civmodcore-paper/src/main/java/vg/civcraft/mc/civmodcore/commands/CommandHelpers.java
  plugins/civmodcore-paper/src/main/java/vg/civcraft/mc/civmodcore/commands/CommandManager.java
  plugins/civmodcore-paper/src/main/java/vg/civcraft/mc/civmodcore/players/PlayerNames.java
Labels: Category: Bug, Priority: Medium

#349 Ignore logins and logouts with `/ignore`
  plugins/civchat2-paper/src/main/java/vg/civcraft/mc/civchat2/listeners/CivChat2Listener.java
Labels: Category: Feature, Priority: Medium

#356 Create PVP Server Container
  .github/workflows/check_gradle_all.yaml
  .github/workflows/comment_on_pr.yaml
  .github/workflows/lint_yaml.yaml
  .github/workflows/on_pr_updated.yaml
  .github/workflows/on_pr_updated_completed.yaml
  .github/workflows/on_tag_pushed.yaml
  .github/workflows/publish_container.yaml
  .github/workflows/publish_gradle_project.yaml
  .github/workflows/release_gradle_project.yaml
  .gitignore
  README.md
  containers/provisioning/grafana/dashboards/default.yml
  containers/provisioning/grafana/dashboards/files/unified-metrics.json
  containers/provisioning/grafana/datasources/influx.yml
  containers/provisioning/mariadb/docker-entrypoint-initdb.d/0100_create_databases.sql
  containers/provisioning/postgres/docker-entrypoint-initdb.d/0100_create_databases.sql
  containers/pvp/Dockerfile
  containers/pvp/config/ops.json
  containers/pvp/config/plugins/TAB/config.yml
  containers/pvp/plugins/TAB-3.1.1.jar
  docker-compose.yml
Labels: Category: Feature, Priority: High

#374 Prevent respawn anchors being used as anti-place
  plugins/simpleadminhacks-paper/src/main/java/com/programmerdan/minecraft/simpleadminhacks/hacks/GameFixes.java
Labels: Category: Feature, Priority: Low

#376 Allow interacting with chests and trapdoors if doing so would not actually open them
  plugins/citadel-paper/src/main/java/vg/civcraft/mc/citadel/listener/BlockListener.java
Labels: Category: Feature, Priority: Low

#384 Fix NPE in CivChat
  plugins/civchat2-paper/src/main/java/vg/civcraft/mc/civchat2/listeners/CivChat2Listener.java
  plugins/civchat2-paper/src/main/java/vg/civcraft/mc/civchat2/utility/ScoreboardHUD.java
Labels: Category: Bug, Priority: Medium

#385 Replace HashSet with OpenObjectHashSet
  plugins/civmodcore-paper/src/main/java/vg/civcraft/mc/civmodcore/world/locations/SparseQuadTree.java
Labels: Category: Feature, Priority: Medium

#387 Add logging for ChunkMeta
  plugins/civmodcore-paper/src/main/java/vg/civcraft/mc/civmodcore/CivModCorePlugin.java
  plugins/civmodcore-paper/src/main/java/vg/civcraft/mc/civmodcore/commands/ChunkMetaCommand.java
  plugins/civmodcore-paper/src/main/java/vg/civcraft/mc/civmodcore/world/locations/chunkmeta/ChunkCoord.java
  plugins/civmodcore-paper/src/main/java/vg/civcraft/mc/civmodcore/world/locations/chunkmeta/ChunkMetaListener.java
  plugins/civmodcore-paper/src/main/java/vg/civcraft/mc/civmodcore/world/locations/chunkmeta/WorldChunkMetaManager.java
  plugins/civmodcore-paper/src/main/java/vg/civcraft/mc/civmodcore/world/locations/chunkmeta/block/table/TableBasedBlockChunkMeta.java
Labels: Category: Feature, Priority: High
