Repository CivMC/Civ, pull requests merged in 2024-05, with the labels that each got.

#394 Fix Factory Overflow
  plugins/civmodcore-paper/src/main/java/vg/civcraft/mc/civmodcore/inventory/items/ItemMap.java
  plugins/factorymod-paper/src/main/java/com/github/igotyou/FactoryMod/factories/FurnCraftChestFactory.java
  plugins/factorymod-paper/src/main/java/com/github/igotyou/FactoryMod/recipes/DecompactingRecipe.java
  plugins/factorymod-paper/src/main/java/com/github/igotyou/FactoryMod/recipes/IRecipe.java
  plugins/factorymod-paper/src/main/java/com/github/igotyou/FactoryMod/recipes/PlayerHeadRecipe.java
  plugins/factorymod-paper/src/main/java/com/github/igotyou/FactoryMod/recipes/PrintBookRecipe.java
  plugins/factorymod-paper/src/main/java/com/github/igotyou/FactoryMod/recipes/PrintNoteRecipe.java
  plugins/factorymod-paper/src/main/java/com/github/igotyou/FactoryMod/recipes/PrintingPlateJsonRecipe.java
  plugins/factorymod-paper/src/main/java/com/github/igotyou/FactoryMod/recipes/PrintingPlateRecipe.java
  plugins/factorymod-paper/src/main/java/com/github/igotyou/FactoryMod/recipes/ProductionRecipe.java
  plugins/factorymod-paper/src/main/java/com/github/igotyou/FactoryMod/recipes/RandomOutputRecipe.java
Labels: Category: Bug, Priority: High

#404 Refactor /ignorelist command
  plugins/civchat2-paper/src/main/java/vg/civcraft/mc/civchat2/commands/IgnoreList.java
Labels: Category: Feature, Priority: Medium

#386 Fix portal hack not triggering
  plugins/simpleadminhacks-paper/src/main/java/com/programmerdan/minecraft/simpleadminhacks/hacks/basic/PortalModifyHack.java
Labels: Category: Bug, Priority: High

#383 Proper /nldg confirmation
  plugins/namelayer-paper/src/main/java/vg/civcraft/mc/namelayer/command/commands/DeleteGroup.java
Labels: Category: Feature, Priority: Low, Meta: Needs Discussion

#347 Don't heal dead entities with health potions
  plugins/finale-paper/src/main/java/com/github/maxopoly/finale/listeners/PotionListener.java
Labels: Category: Bug, Priority: Medium

#350 Add `/nllim` (Name Layer List Invited Members)
  plugins/namelayer-paper/src/main/java/vg/civcraft/mc/namelayer/command/CommandHandler.java
  plugins/namelayer-paper/src/main/java/vg/civcraft/mc/namelayer/command/commands/ListInvites.java
  plugins/namelayer-paper/src/main/java/vg/civcraft/mc/namelayer/group/Group.java
Labels: Category: Feature, Priority: High

#511 Fix Mangrove/cherry saplings
  ansible/files/paper-config/plugins/RealisticBiomes/config.yml
Labels: Category: Bug, Priority: High

#526 Fix Emotes
  ansible/files/paper-config/plugins/GEmote/config.yml
  ansible/files/paper-config/plugins/GEmote/emotes/Aqua-trail.gex
  ansible/files/paper-config/plugins/GEmote/emotes/Fire-trail.gex
  ansible/files/paper-config/plugins/GEmote/emotes/Gold-trail.gex
  ansible/files/paper-config/plugins/GEmote/emotes/Love-trail.gex
  ansible/files/paper-config/plugins/GEmote/emotes/Music-trail.gex
  ansible/files/paper-config/plugins/GEmote/emotes/Orange-trail.gex
  ansible/files/paper-config/plugins/GEmote/emotes/Pink-trail.gex
  ansible/files/paper-config/plugins/GEmote/emotes/Red-trail.gex
  ansible/files/paper-config/plugins/GEmote/emotes/Smoke-trail.gex
  ansible/files/paper-config/plugins/GEmote/emotes/Soul-Fire-trail.gex
  ansible/files/paper-config/plugins/GEmote/emotes/black-trail.gex
  ansible/files/paper-config/plugins/GEmote/emotes/blue-trail.gex
  ansible/files/paper-config/plugins/GEmote/emotes/green-trail.gex
  ansible/files/paper-plugins/GEmote-1.0.1.jar
Labels: Category: Bug, Priority: High

#489 Superfriend snitch fix
  ansible/files/paper-config/plugins/CivDuties/config.yml
Labels: Category: Bug, Priority: High

#531 Fix pearled players going through portals
  plugins/simpleadminhacks-paper/src/main/java/com/programmerdan/minecraft/simpleadminhacks/hacks/basic/PortalModifyHack.java
Labels: Category: Bug, Priority: High

#535 Revert "Discard entities before adding NPCs"
  plugins/combattagplus-paper/src/main/java/net/minelink/ctplus/nms/NpcPlayer.java
  plugins/combattagplus-paper/src/main/java/net/minelink/ctplus/nms/NpcPlayerHelperImpl.java
Labels: Category: Bug, Priority: High

#488 Fix Command Created Factory IO
  plugins/factorymod-paper/src/main/java/com/github/igotyou/FactoryMod/commands/Create.java
Labels: Category: Bug, Priority: Medium

#538 Fix some snitches crashing the server
  plugins/jukealert-paper/src/main/java/com/untamedears/jukealert/database/JukeAlertDAO.java
Labels: Category: Bug, Priority: High
