Repository CivMC/Civ, pull requests merged in 2024-07, with the labels that each got.

#540 add missing mobs
  ansible/files/paper-config/plugins/SimpleAdminHacks/config.yml
Labels: Category: Bug, Priority: Low

#571 Move editorconfig
  .editorconfig
Labels: Category: Technical Debt

#561 Increase MaxPowerTransfers
  ansible/files/paper-config/plugins/CastleGates/config.yml
Labels: Category: Bug

#566 Remove outdated game fixes
  plugins/simpleadminhacks-paper/src/main/java/com/programmerdan/minecraft/simpleadminhacks/configs/GameFixesConfig.java
  plugins/simpleadminhacks-paper/src/main/java/com/programmerdan/minecraft/simpleadminhacks/hacks/GameFixes.java
  plugins/simpleadminhacks-paper/src/main/resources/config.yml
Labels: Category: Bug
