Repository CivMC/Civ, pull requests merged in 2024-02, with the labels that each got.

#10 Add a fix for high despawn ranges
  plugins/simpleadminhacks-paper/src/main/java/com/programmerdan/minecraft/simpleadminhacks/hacks/basic/DespawnFix.java
  plugins/simpleadminhacks-paper/src/main/resources/config.yml
Labels: Category: Bug, Priority: High

#9 Fix lag when loading the Name_layer_special group
  plugins/namelayer-paper/src/main/java/vg/civcraft/mc/namelayer/database/GroupManagerDao.java
Labels: Category: Bug, Priority: High

#1 Make the /nl GUI easier to use
  plugins/namelayer-paper/src/main/java/vg/civcraft/mc/namelayer/gui/GUIGroupOverview.java
  plugins/namelayer-paper/src/main/java/vg/civcraft/mc/namelayer/gui/MainGroupGUI.java
Labels: Category: Enchancement, Priority: High

#8 Don't use snapshots with getHolder
  plugins/citadel-paper/src/main/java/vg/civcraft/mc/citadel/listener/InventoryListener.java
  plugins/exilepearl-paper/src/main/java/com/devotedmc/ExilePearl/listener/ExileListener.java
  plugins/exilepearl-paper/src/main/java/com/devotedmc/ExilePearl/listener/PlayerListener.java
Labels: Category: Technical Debt, Priority: Medium

#6 Remove unused item-maker classes
  plugins/civmodcore-paper/src/main/java/vg/civcraft/mc/civmodcore/inventory/items/ItemBuilder.java
  plugins/civmodcore-paper/src/main/java/vg/civcraft/mc/civmodcore/inventory/items/ItemFactory.java
Labels: Category: Technical Debt, Priority: Medium

#7 Remove unused SkinCache
  plugins/civmodcore-paper/src/main/java/vg/civcraft/mc/civmodcore/util/SkinCache.java
Labels: Category: Technical Debt, Priority: Medium

#5 Fix and optimise ACF extensions
  plugins/civmodcore-paper/src/main/java/vg/civcraft/mc/civmodcore/commands/CommandHelpers.java
  plugins/civmodcore-paper/src/main/java/vg/civcraft/mc/civmodcore/commands/CommandManager.java
Labels: Category: Enchancement, Priority: Medium

#4 Remove asTranslatable
  plugins/civmodcore-paper/src/main/java/vg/civcraft/mc/civmodcore/entities/EntityUtils.java
  plugins/civmodcore-paper/src/main/java/vg/civcraft/mc/civmodcore/inventory/items/EnchantUtils.java
  plugins/civmodcore-paper/src/main/java/vg/civcraft/mc/civmodcore/inventory/items/ItemUtils.java
  plugins/civmodcore-paper/src/main/java/vg/civcraft/mc/civmodcore/inventory/items/MaterialUtils.java
  plugins/civmodcore-paper/src/main/java/vg/civcraft/mc/civmodcore/inventory/items/PotionUtils.java
Labels: Category: Technical Debt, Priority: Medium

#237 Add Map Copy Protection
  plugins/simpleadminhacks-paper/src/main/java/com/programmerdan/minecraft/simpleadminhacks/hacks/basic/MapCopyProtection.java
  plugins/simpleadminhacks-paper/src/main/resources/config.yml
  plugins/simpleadminhacks-paper/src/main/resources/plugin.yml
Labels: Category: Feature, Priority: High

#238 Prevent Innapropriate Flower Pot Modification
  plugins/citadel-paper/src/main/java/vg/civcraft/mc/citadel/listener/BlockListener.java
Labels: Category: Bug, Priority: Medium

#239 Fix "Smart" Mobs Being Able To Open Reinforced Doors
  plugins/citadel-paper/src/main/java/vg/civcraft/mc/citadel/listener/EntityListener.java
Labels: Category: Bug, Priority: Medium

#262 Fix primary owner transfer not being set to OWNER role
  plugins/namelayer-paper/src/main/java/vg/civcraft/mc/namelayer/command/commands/TransferGroup.java
Labels: Category: Bug, Priority: High

#236 Make `/janame` feedback a bit nicer
  plugins/jukealert-paper/src/main/java/com/untamedears/jukealert/commands/NameCommand.java
Labels: Category: Feature, Priority: Medium

#241 Fixup LoggableBlockAction (fixes #213)
  plugins/jukealert-paper/src/main/java/com/untamedears/jukealert/model/actions/abstr/LoggableBlockAction.java
Labels: Category: Bug, Priority: Low

#255 Fix show next page
  plugins/namelayer-paper/src/main/java/vg/civcraft/mc/namelayer/gui/MainGroupGUI.java
Labels: Category: Bug, Priority: Medium

#256 Fix show previous page
  plugins/namelayer-paper/src/main/java/vg/civcraft/mc/namelayer/gui/MainGroupGUI.java
Labels: Category: Bug, Priority: Medium

#275 Optimise snitch GUI
  plugins/civmodcore-paper/src/main/java/vg/civcraft/mc/civmodcore/inventory/gui/FastMultiPageView.java
  plugins/jukealert-paper/src/main/java/com/untamedears/jukealert/gui/SnitchOverviewGUI.java
  plugins/jukealert-paper/src/main/resources/plugin.yml
Labels: Category: Bug, Priority: High

#273 Add BetterRails, FasterHorses, CopperRail, and miscellaneous things
  plugins/simpleadminhacks-paper/src/main/java/com/programmerdan/minecraft/simpleadminhacks/configs/BetterRailsConfig.java
  plugins/simpleadminhacks-paper/src/main/java/com/programmerdan/minecraft/simpleadminhacks/framework/HackManager.java
  plugins/simpleadminhacks-paper/src/main/java/com/programmerdan/minecraft/simpleadminhacks/framework/commands/CommandRegistrar.java
  plugins/simpleadminhacks-paper/src/main/java/com/programmerdan/minecraft/simpleadminhacks/framework/commands/HacksCommand.java
  plugins/simpleadminhacks-paper/src/main/java/com/programmerdan/minecraft/simpleadminhacks/hacks/BetterRails.java
  plugins/simpleadminhacks-paper/src/main/java/com/programmerdan/minecraft/simpleadminhacks/hacks/HorseStats.java
  plugins/simpleadminhacks-paper/src/main/java/com/programmerdan/minecraft/simpleadminhacks/hacks/basic/CopperRail.java
  plugins/simpleadminhacks-paper/src/main/java/com/programmerdan/minecraft/simpleadminhacks/hacks/basic/FasterHorses.java
  plugins/simpleadminhacks-paper/src/main/java/com/programmerdan/minecraft/simpleadminhacks/hacks/basic/StriderBreeding.java
  plugins/simpleadminhacks-paper/src/main/resources/config.yml
Labels: Category: Feature, Priority: High

#242 Improve time formatting in snitch logs
  plugins/jukealert-paper/src/main/java/com/untamedears/jukealert/model/actions/abstr/LoggablePlayerAction.java
  plugins/jukealert-paper/src/main/java/com/untamedears/jukealert/model/actions/abstr/PlayerAction.java
Labels: Category: Feature, Priority: Medium

#319 Add a toggle to enable/disable banned pearls in ep showall
  plugins/exilepearl-paper/src/main/java/com/devotedmc/ExilePearl/command/CmdShowAllPearls.java
Labels: Category: Feature, Priority: Medium

#263 Remove Lombok :(
  plugins/itemexchange-paper/build.gradle.kts
  plugins/itemexchange-paper/src/main/java/com/untamedears/itemexchange/utility/ModifierStorage.java
  plugins/itemexchange-paper/src/main/java/com/untamedears/itemexchange/utility/Utilities.java
Labels: Category: Technical Debt, Priority: Low

#329 Add workflows for PR checks
  .github/workflows/check_gradle_all.yaml
  .github/workflows/comment_on_pr.yaml
  .github/workflows/lint_yaml.yaml
  .github/workflows/on_pr_updated.yaml
  .github/workflows/on_pr_updated_completed.yaml
  .yamllint.yaml
Labels: Category: Feature
