Repository CivMC/Civ, pull requests merged in 2025-01, with the labels that each got.

#565 Change fuel button to left shift
  plugins/civmodcore-paper/src/main/java/vg/civcraft/mc/civmodcore/inventory/gui/IClickable.java
  plugins/factorymod-paper/src/main/java/com/github/igotyou/FactoryMod/utility/IOConfigSection.java
Labels: Category: Bug, awaiting response

#729 fix mobs spawning/stuck outside simulation distance
  ansible/files/paper-config/config/paper-world-defaults.yml
Labels: Category: Bug

#727 Add missing blocks to castlegate
  ansible/files/paper-config/plugins/CastleGates/config.yml
Labels: Category: Feature

#726 Remove Evenmorefish from civ repo.
  ansible/files/paper-config/plugins/EvenMoreFish/baits.yml
  ansible/files/paper-config/plugins/EvenMoreFish/competitions.yml
  ansible/files/paper-config/plugins/EvenMoreFish/config.yml
  ansible/files/paper-config/plugins/EvenMoreFish/fish.yml
  ansible/files/paper-config/plugins/EvenMoreFish/messages.yml
  ansible/files/paper-config/plugins/EvenMoreFish/rarities.yml
Labels: Category: Bug
